[package]
name = "import-organizer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "imporg"
path = "src/main.rs"

[dependencies]
criterion = "0.5.1"

[[bench]]
name = "import_organizer_benchmark"
harness = false

