[package]
name = "import-organizer"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"

[[bench]]
name = "import_organizer_benchmark"
harness = false

[lib]
name = "import_organizer"
path = "src/lib.rs"
